dual_arm_gripper_position_control:
  type: position_controllers/JointTrajectoryController
  joints:
    - arm_0_shoulder_pan_joint
    - arm_0_shoulder_lift_joint
    - arm_0_elbow_joint
    - arm_0_wrist_1_joint
    - arm_0_wrist_2_joint
    - arm_0_wrist_3_joint
    - gripper_0_finger_joint
    - arm_1_shoulder_pan_joint
    - arm_1_shoulder_lift_joint
    - arm_1_elbow_joint
    - arm_1_wrist_1_joint
    - arm_1_wrist_2_joint
    - arm_1_wrist_3_joint
    - gripper_1_finger_joint
  gains:
    arm_0_shoulder_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_0_shoulder_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_0_elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_0_wrist_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_0_wrist_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_0_wrist_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    gripper_0_finger_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_1_shoulder_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_1_shoulder_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_1_elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_1_wrist_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_1_wrist_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_1_wrist_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    gripper_1_finger_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1